Resources:
  MainTodoHandlerSheharyarServiceRole8F41B26C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TodoAppStack/MainTodoHandlerSheharyar/ServiceRole/Resource
  MainTodoHandlerSheharyarServiceRoleDefaultPolicyF92F7B91:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - TableTodosSheharyar8AC8847A
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: MainTodoHandlerSheharyarServiceRoleDefaultPolicyF92F7B91
      Roles:
        - Ref: MainTodoHandlerSheharyarServiceRole8F41B26C
    Metadata:
      aws:cdk:path: TodoAppStack/MainTodoHandlerSheharyar/ServiceRole/DefaultPolicy/Resource
  MainTodoHandlerSheharyar3C85775A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6S3BucketA3E8C674
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6S3VersionKey0A2077EE
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6S3VersionKey0A2077EE
      Role:
        Fn::GetAtt:
          - MainTodoHandlerSheharyarServiceRole8F41B26C
          - Arn
      Environment:
        Variables:
          TABLE:
            Ref: TableTodosSheharyar8AC8847A
      Handler: index.handler
      Runtime: nodejs12.x
    DependsOn:
      - MainTodoHandlerSheharyarServiceRoleDefaultPolicyF92F7B91
      - MainTodoHandlerSheharyarServiceRole8F41B26C
    Metadata:
      aws:cdk:path: TodoAppStack/MainTodoHandlerSheharyar/Resource
      aws:asset:path: H:\AWS Practice\TodoApp\lambda
      aws:asset:property: Code
  GraphEndPointSheharyarFF4F1F3D:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: todo-app-graph-endpoint-sheharyar
      XrayEnabled: true
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/Resource
  GraphEndPointSheharyarSchemaCBB1D47D:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
      Definition: "type Todo {\r

        \  userId: String!\r

        \  title: String!\r

        \  isCompleted: Boolean!\r

        \  docId: String!\r

        }\r

        type Query {\r

        \  todos: [Todo]!\r

        }\r

        type Mutation {\r

        \  addTodo(title: String!): Todo!\r

        \  markAsCompleted(docId: ID!): Todo!\r

        }\r\n"
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/Schema
  GraphEndPointSheharyarDefaultApiKeyEBE69BF7:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
    DependsOn:
      - GraphEndPointSheharyarSchemaCBB1D47D
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/DefaultApiKey
  GraphEndPointSheharyarGraphDynamoDataSourceSheharyarServiceRoleFE4ECF2F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/GraphDynamoDataSourceSheharyar/ServiceRole/Resource
  ? GraphEndPointSheharyarGraphDynamoDataSourceSheharyarServiceRoleDefaultPolicy17F57F59
  : Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - MainTodoHandlerSheharyar3C85775A
                - Arn
        Version: "2012-10-17"
      PolicyName: GraphEndPointSheharyarGraphDynamoDataSourceSheharyarServiceRoleDefaultPolicy17F57F59
      Roles:
        - Ref: GraphEndPointSheharyarGraphDynamoDataSourceSheharyarServiceRoleFE4ECF2F
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/GraphDynamoDataSourceSheharyar/ServiceRole/DefaultPolicy/Resource
  GraphEndPointSheharyarGraphDynamoDataSourceSheharyar9503BA25:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
      Name: GraphDynamoDataSourceSheharyar
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn:
          Fn::GetAtt:
            - MainTodoHandlerSheharyar3C85775A
            - Arn
      ServiceRoleArn:
        Fn::GetAtt:
          - GraphEndPointSheharyarGraphDynamoDataSourceSheharyarServiceRoleFE4ECF2F
          - Arn
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/GraphDynamoDataSourceSheharyar/Resource
  GraphEndPointSheharyarMutationaddTodoResolver7ED9220D:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
      FieldName: addTodo
      TypeName: Mutation
      DataSourceName: GraphDynamoDataSourceSheharyar
      Kind: UNIT
    DependsOn:
      - GraphEndPointSheharyarGraphDynamoDataSourceSheharyar9503BA25
      - GraphEndPointSheharyarSchemaCBB1D47D
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/MutationaddTodoResolver/Resource
  GraphEndPointSheharyarMutationmarkAsCompletedResolverD9871409:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
      FieldName: markAsCompleted
      TypeName: Mutation
      DataSourceName: GraphDynamoDataSourceSheharyar
      Kind: UNIT
    DependsOn:
      - GraphEndPointSheharyarGraphDynamoDataSourceSheharyar9503BA25
      - GraphEndPointSheharyarSchemaCBB1D47D
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/MutationmarkAsCompletedResolver/Resource
  GraphEndPointSheharyarQuerytodosResolverD7703B20:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - GraphEndPointSheharyarFF4F1F3D
          - ApiId
      FieldName: todos
      TypeName: Query
      DataSourceName: GraphDynamoDataSourceSheharyar
      Kind: UNIT
    DependsOn:
      - GraphEndPointSheharyarGraphDynamoDataSourceSheharyar9503BA25
      - GraphEndPointSheharyarSchemaCBB1D47D
    Metadata:
      aws:cdk:path: TodoAppStack/GraphEndPointSheharyar/QuerytodosResolver/Resource
  TableTodosSheharyar8AC8847A:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: docId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: docId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: todos
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: TodoAppStack/TableTodosSheharyar/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.86.0,@aws-cdk/assets=1.86.0,@aws-cdk/aws-applicationautoscaling=1.86.0,@aws-cdk/aws-appsync=1.86.0,@aws-cdk/aws-autoscaling-common=1.86.0,@aws-cdk/aws-cloudwatch=1.86.0,@aws-cdk/aws-codeguruprofiler=1.86.0,@aws-cdk/aws-dynamodb=1.86.0,@aws-cdk/aws-ec2=1.86.0,@aws-cdk/aws-ecr=1.86.0,@aws-cdk/aws-ecr-assets=1.86.0,@aws-cdk/aws-events=1.86.0,@aws-cdk/aws-iam=1.86.0,@aws-cdk/aws-kms=1.86.0,@aws-cdk/aws-lambda=1.86.0,@aws-cdk/aws-logs=1.86.0,@aws-cdk/aws-s3=1.86.0,@aws-cdk/aws-s3-assets=1.86.0,@aws-cdk/aws-sqs=1.86.0,@aws-cdk/aws-ssm=1.86.0,@aws-cdk/cloud-assembly-schema=1.86.0,@aws-cdk/core=1.86.0,@aws-cdk/custom-resources=1.86.0,@aws-cdk/cx-api=1.86.0,@aws-cdk/region-info=1.86.0,jsii-runtime=node.js/v14.15.3
    Metadata:
      aws:cdk:path: TodoAppStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  ? AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6S3BucketA3E8C674
  : Type: String
    Description: S3 bucket for asset "cb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6"
  ? AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6S3VersionKey0A2077EE
  : Type: String
    Description: S3 key for asset version "cb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6"
  ? AssetParameterscb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6ArtifactHash57FF4298
  : Type: String
    Description: Artifact hash for asset "cb3b9c0d20a24abd1a345d991d217778509e31247b4333e4e5fd1ddfd19425f6"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
