/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://kpge7h6bzffu3f66wj3hamtodi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "region": "ap-south-1",
        "userPoolId": "ap-south-1_I7pIgOTKI",
        "userPoolWebClientId": "3bqj0cshib2ip6q5e9ei8fmrd1"
    }
};


export default awsmobile;
